export const DOCTOR_NAV = [
  { to: '/doctor', label: 'Overview', icon: 'fa-chart-line' },
  { to: '/doctor/appointments', label: 'Appointments', icon: 'fa-calendar-check' },
  { to: '/doctor/calendar', label: 'Calendar', icon: 'fa-calendar-days' },
  { to: '/doctor/patients', label: 'Patients', icon: 'fa-users' },
  { to: '/doctor/search', label: 'Advanced Search', icon: 'fa-magnifying-glass-plus' },
  { to: '/doctor/treatment-journey', label: 'Treatment Journey', icon: 'fa-notes-medical' },
  { to: '/doctor/packages', label: 'Enrollments', icon: 'fa-user-plus' },
  { to: '/doctor/treatment-services', label: 'Services & treatments', icon: 'fa-hand-holding-medical' },
  { to: '/doctor/service-packages', label: 'My packages', icon: 'fa-box-open' },
  { to: '/doctor/admin-package-prices', label: 'Platform prices', icon: 'fa-tags' },
  { to: '/doctor/prescriptions', label: 'Rehab Plans', icon: 'fa-dumbbell' },
  { to: '/doctor/documents', label: 'Documents', icon: 'fa-folder-tree' },
  { to: '/clinic-manage', label: 'Clinic Analytics', icon: 'fa-hospital-user' },
  { to: '/doctor/clinics', label: 'My Clinics', icon: 'fa-hospital' },
  { to: '/doctor/clinics/new', label: 'Add Clinic', icon: 'fa-plus' },
  { to: '/doctor/clinic-availability', label: 'Availability', icon: 'fa-calendar-days' },
  { to: '/doctor/booking-filters', label: 'Booking filters', icon: 'fa-filter' },
  { to: '/doctor/custom-slots', label: 'Custom Slots', icon: 'fa-calendar-plus' },
  { to: '/doctor/requests', label: 'Reschedule / cancel', icon: 'fa-inbox' },
  { to: '/doctor/emergency', label: 'Emergency', icon: 'fa-truck-medical' },
  { to: '/doctor/notifications', label: 'Notifications', icon: 'fa-bell', notifyKey: true },
  { to: '/doctor/earnings', label: 'Earnings', icon: 'fa-indian-rupee-sign' },
  { to: '/doctor/profile', label: 'Profile', icon: 'fa-user-gear' },
];
